"use client";

import React, { useState } from "react";
import * as motion from "framer-motion/client";
import { AnimatePresence } from "framer-motion";
import { ChevronDown } from "lucide-react";

const faqs = [
    {
        question: "What is IIoT and how is it different from IoT?",
        answer: "IIoT (Industrial Internet of Things) focuses on industrial applications like manufacturing, energy, and logistics, prioritizing reliability, security, and precision over consumer convenience."
    },
    {
        question: "Can you retrofit my legacy machines?",
        answer: "Yes, we specialize in retrofitting. We use non-intrusive sensors and gateways to extract data from legacy PLCs and machinery without replacing expensive equipment."
    },
    {
        question: "What protocols do you support?",
        answer: "We support industry-standard protocols including MQTT, OPC UA, Modbus TCP/RTU, Profibus, and wireless standards like LoRaWAN, Zigbee, and BLE."
    },
    {
        question: "Is the data transmission secure?",
        answer: "Absolutely. We implement X.509 certificate-based authentication, TLS encryption for data in transit, and secure boot for hardware to prevent unauthorized access."
    },
    {
        question: "Do you offer Edge Computing solutions?",
        answer: "Yes. For low-latency requirements, we process data locally on edge devices (like Raspberry Pi or industrial gateways) and only send aggregated insights to the cloud."
    },
    {
        question: "Who owns the data generated by the devices?",
        answer: "You do. We build the infrastructure to collect and visualize the data, but you retain full ownership and control over your proprietary industrial data."
    }
];

const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { type: "spring" as const, stiffness: 100, damping: 15 } }
};

const FAQItem = ({ faq, index, activeIndex, toggleFAQ }: any) => {
    const isActive = activeIndex === index;
    return (
        <motion.div
            variants={itemVariants}
            whileHover={{ scale: 1.02 }}
            className={`rounded-xl p-5 shadow-sm border transition-all duration-300 h-fit ${isActive ? "bg-white border-[#10b981]/30 shadow-md" : "bg-white border-slate-100 hover:shadow-md"}`}
        >
            <button onClick={() => toggleFAQ(index)} className="flex items-center justify-between w-full text-left group gap-4">
                <span className={`text-base sm:text-lg font-medium transition-colors duration-300 ${isActive ? "text-[#10b981]" : "text-[#3A0F67] group-hover:text-[#10b981]"}`}>
                    {faq.question}
                </span>
                <motion.div animate={{ rotate: isActive ? 180 : 0 }} className={`shrink-0 ${isActive ? "text-[#10b981]" : "text-slate-400"}`}>
                    <ChevronDown className="w-5 h-5 sm:w-6 sm:h-6" />
                </motion.div>
            </button>
            <AnimatePresence>
                {isActive && (
                    <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden">
                        <div className="pt-3 text-slate-600 text-sm sm:text-base leading-relaxed">{faq.answer}</div>
                    </motion.div>
                )}
            </AnimatePresence>
        </motion.div>
    );
};

export default function IiotFAQ() {
    const [activeIndex, setActiveIndex] = useState<number | null>(null);
    const toggleFAQ = (index: number) => setActiveIndex(activeIndex === index ? null : index);
    const leftFaqs = faqs.filter((_, i) => i % 2 === 0);
    const rightFaqs = faqs.filter((_, i) => i % 2 !== 0);

    return (
        <section className="py-24 bg-slate-50 relative overflow-hidden">
            <div className="max-w-7xl mx-auto px-6 lg:px-8">
                <div className="text-center mb-16">
                    <span className="text-[#10b981] font-bold tracking-widest uppercase text-sm mb-4 block">FAQ</span>
                    <h2 className="text-4xl lg:text-5xl font-extrabold text-[#3A0F67] mb-6">IIoT <span className="text-[#10b981]">Questions</span></h2>
                </div>
                <motion.div className="flex flex-col md:flex-row gap-4 lg:gap-6" initial="hidden" whileInView="visible" viewport={{ once: true }}>
                    <div className="flex flex-col gap-4 w-full md:w-1/2">{leftFaqs.map((faq, i) => <FAQItem key={i} faq={faq} index={faqs.indexOf(faq)} activeIndex={activeIndex} toggleFAQ={toggleFAQ} />)}</div>
                    <div className="flex flex-col gap-4 w-full md:w-1/2">{rightFaqs.map((faq, i) => <FAQItem key={i} faq={faq} index={faqs.indexOf(faq)} activeIndex={activeIndex} toggleFAQ={toggleFAQ} />)}</div>
                </motion.div>
            </div>
        </section>
    );
}
